"""empty message

Revision ID: 44b12e46589c
Revises: c3432f8ce560
Create Date: 2019-10-10 17:48:07.379032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44b12e46589c'
down_revision = 'c3432f8ce560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('shop_name', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=128), nullable=True),
    sa.Column('time_format', sa.String(length=128), nullable=True),
    sa.Column('week_start', sa.String(length=128), nullable=True),
    sa.Column('appointment_color_source', sa.String(length=128), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('facebook_page', sa.String(length=255), nullable=True),
    sa.Column('instagram_page', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_name')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('location_name', sa.String(length=255), nullable=False),
    sa.Column('contact_number', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('street_address', sa.String(length=255), nullable=False),
    sa.Column('apt_suite_building', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=150), nullable=False),
    sa.Column('state', sa.String(length=150), nullable=False),
    sa.Column('zip_code', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location')
    op.drop_table('account')
    # ### end Alembic commands ###
