"""empty message

Revision ID: c3432f8ce560
Revises: c6ce99817bf5
Create Date: 2019-10-10 17:17:40.613950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3432f8ce560'
down_revision = 'c6ce99817bf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('jwt_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'jwt_token')
    # ### end Alembic commands ###
