"""empty message

Revision ID: c6ce99817bf5
Revises: e89882dc715e
Create Date: 2019-10-09 17:28:04.268899

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c6ce99817bf5'
down_revision = 'e89882dc715e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'address',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('user', 'first_name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('user', 'last_name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('user', 'phone',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('user', 'role',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=True)
    op.alter_column('user', 'status',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=True)
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', mysql.VARCHAR(length=128), nullable=False))
    op.alter_column('user', 'status',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=False)
    op.alter_column('user', 'role',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=False)
    op.alter_column('user', 'phone',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('user', 'last_name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('user', 'first_name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('user', 'address',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###
